In [2]:
import math as mt
mt.sqrt(10)

3.1622776601683795

In [4]:
#how to create numoy arrays
import numpy as np
l =[1,2,3]
np.array(l)


array([1, 2, 3])

In [20]:
a=np.zeros((2,3,4,5),int)
a

array([[[[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]]],


       [[[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]]]])

In [23]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
b.shape

(2, 3)

In [26]:
b[0] # accessing all the rows

array([1, 2, 3])

In [28]:
b[:, 0] # accessing 0th column

array([1, 4])

In [30]:
b[0:2, 0] # acessing complete column of 0th and 1st row

array([1, 4])

In [32]:
b[0:2, 1:3]

array([[2, 3],
       [5, 6]])

In [37]:
#numpy Operations
a = np.array([3,4,5])
b = np.array([7,8,9])

print(a*b)# 3l3m3nt wise multiplication
print(a *2)
print(a **2)
print(a ** b)


[21 32 45]
[ 6  8 10]
[ 9 16 25]
[   2187   65536 1953125]


In [44]:
int(a.mean()) #by default it is of float type

4

In [47]:
#Euclidean distance between two points
a = np.array([3,4,5])
b = np.array([7,8,9])

c = ((a-b)**2).sum()

d = mt.sqrt(c)
d



6.928203230275509